#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.2 on Thu Feb 23 17:06:17 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Manufacturer"))
        self.manufacturer_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Product Number"))
        self.product_number_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("Calibration Number"))
        self.calibration_number_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("Serial Number"))
        self.serial_number_component_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_5 = wx.StaticText(self, wx.ID_ANY, _("Firmware Version"))
        self.firmware_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.component_submit_button = wx.Button(self, wx.ID_ANY, _("Submit"))
        self.component_clear_button = wx.Button(self, wx.ID_ANY, _("Clear"))
        self.label_6 = wx.StaticText(self, wx.ID_ANY, _("Name"))
        self.tower_name_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_7 = wx.StaticText(self, wx.ID_ANY, _("Serial Number"))
        self.serial_number_tower_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_8 = wx.StaticText(self, wx.ID_ANY, _("ID In Company"))
        self.id_tower_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_9 = wx.StaticText(self, wx.ID_ANY, _("Geolocation"))
        self.location_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_10 = wx.StaticText(self, wx.ID_ANY, _("Alias"))
        self.tower_alias_text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.tower_submit_button = wx.Button(self, wx.ID_ANY, _("Submit"))
        self.tower_clear_button = wx.Button(self, wx.ID_ANY, _("Clear"))
        self.tree_control = wx.TreeCtrl(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("ID In Company"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(1, 2, 0, 0)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        tower_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.GridSizer(5, 2, 5, 5)
        self.comonent_buttons = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.GridSizer(5, 2, 5, 5)
        grid_sizer_2.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.manufacturer_text, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.product_number_text, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.calibration_number_text, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.serial_number_component_text, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_2.Add(self.firmware_text, 0, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_2, 1, 0, 0)
        sizer_8.Add(self.component_submit_button, 0, wx.ALIGN_RIGHT, 0)
        self.comonent_buttons.Add(sizer_8, 1, 0, 0)
        sizer_9.Add(self.component_clear_button, 0, 0, 0)
        self.comonent_buttons.Add(sizer_9, 1, 0, 0)
        sizer_2.Add(self.comonent_buttons, 1, wx.BOTTOM, 0)
        grid_sizer_3.Add(self.label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.tower_name_text, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.serial_number_tower_text, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.id_tower_text, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.location_text, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_3.Add(self.tower_alias_text, 0, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_3, 1, 0, 0)
        sizer_10.Add(self.tower_submit_button, 0, wx.ALIGN_RIGHT, 0)
        tower_buttons.Add(sizer_10, 1, 0, 0)
        sizer_11.Add(self.tower_clear_button, 0, 0, 0)
        tower_buttons.Add(sizer_11, 1, 0, 0)
        sizer_2.Add(tower_buttons, 1, 0, 0)
        grid_sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_5.Add(self.tree_control, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_5, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame
class DescriptionGui(wx.App):
    def OnInit(self):
        frame_1 = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return True

# end of class DescriptionGui

if __name__ == "__main__":
    gettext.install("description") # replace with the appropriate catalog name

    description = DescriptionGui(0)
    description.MainLoop()